
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.20348 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.7.2+d6990bcfa for .NET Framework
      Build started 11/7/2023 9:57:18 AM.
      
      Project "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\3.27.7\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\3.27.7\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\3.27.7\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:02.69
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/3.27.7/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-pgj7fv"
      binary: "D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-pgj7fv"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-pgj7fv'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_a2f22.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.7.2+d6990bcfa for .NET Framework
        Build started 11/7/2023 9:57:21 AM.
        
        Project "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-pgj7fv\\cmTC_a2f22.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_a2f22.dir\\Debug\\".
          Creating directory "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-pgj7fv\\Debug\\".
          Creating directory "cmTC_a2f22.dir\\Debug\\cmTC_a2f22.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_a2f22.dir\\Debug\\cmTC_a2f22.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_a2f22.dir\\Debug\\cmTC_a2f22.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_a2f22.dir\\Debug\\\\" /Fd"cmTC_a2f22.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_a2f22.dir\\Debug\\\\" /Fd"cmTC_a2f22.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-pgj7fv\\Debug\\cmTC_a2f22.exe" /INCREMENTAL /ILK:"cmTC_a2f22.dir\\Debug\\cmTC_a2f22.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-pgj7fv/Debug/cmTC_a2f22.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-pgj7fv/Debug/cmTC_a2f22.lib" /MACHINE:X64  /machine:x64 cmTC_a2f22.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_a2f22.vcxproj -> D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-pgj7fv\\Debug\\cmTC_a2f22.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_a2f22.dir\\Debug\\cmTC_a2f22.tlog\\unsuccessfulbuild".
          Touching "cmTC_a2f22.dir\\Debug\\cmTC_a2f22.tlog\\cmTC_a2f22.lastbuildstate".
        Done Building Project "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-pgj7fv\\cmTC_a2f22.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.91
        
      exitCode: 0
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.20348 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.8.3+195e7f5a3 for .NET Framework
      Build started 12/31/2023 10:12:19 PM.
      
      Project "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\3.27.9\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\3.27.9\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\3.27.9\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:02.90
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/3.27.9/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-ettgvf"
      binary: "D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-ettgvf"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-ettgvf'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_98300.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.8.3+195e7f5a3 for .NET Framework
        Build started 12/31/2023 10:12:23 PM.
        
        Project "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-ettgvf\\cmTC_98300.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_98300.dir\\Debug\\".
          Creating directory "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-ettgvf\\Debug\\".
          Creating directory "cmTC_98300.dir\\Debug\\cmTC_98300.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_98300.dir\\Debug\\cmTC_98300.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_98300.dir\\Debug\\cmTC_98300.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_98300.dir\\Debug\\\\" /Fd"cmTC_98300.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32826.1 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_98300.dir\\Debug\\\\" /Fd"cmTC_98300.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-ettgvf\\Debug\\cmTC_98300.exe" /INCREMENTAL /ILK:"cmTC_98300.dir\\Debug\\cmTC_98300.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-ettgvf/Debug/cmTC_98300.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/a/Data-Structure-Project/Data-Structure-Project/builds/Windows/CMakeFiles/CMakeScratch/TryCompile-ettgvf/Debug/cmTC_98300.lib" /MACHINE:X64  /machine:x64 cmTC_98300.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_98300.vcxproj -> D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-ettgvf\\Debug\\cmTC_98300.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_98300.dir\\Debug\\cmTC_98300.tlog\\unsuccessfulbuild".
          Touching "cmTC_98300.dir\\Debug\\cmTC_98300.tlog\\cmTC_98300.lastbuildstate".
        Done Building Project "D:\\a\\Data-Structure-Project\\Data-Structure-Project\\builds\\Windows\\CMakeFiles\\CMakeScratch\\TryCompile-ettgvf\\cmTC_98300.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.95
        
      exitCode: 0
...
