name: Build Large Int Calculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_DIR: builds

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MinGW (for Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw -y
          refreshenv

      - name: Create build directories
        run: mkdir -p ${{env.BUILD_DIR}}/ubuntu ${{env.BUILD_DIR}}/windows/x64 ${{env.BUILD_DIR}}/windows/x86 ${{env.BUILD_DIR}}/macos

      - name: Compile on Ubuntu
        run: gcc -o ${{env.BUILD_DIR}}/ubuntu/largeintcalculator largeintcalculator.c

      - name: Compile 64-bit Windows
        if: matrix.os == 'windows-latest'
        run: x86_64-w64-mingw32-gcc -o ${{env.BUILD_DIR}}/windows/x64/largeintcalculator.exe largeintcalculator.c

      - name: Compile 32-bit Windows
        if: matrix.os == 'windows-latest'
        run: i686-w64-mingw32-gcc -o ${{env.BUILD_DIR}}/windows/x86/largeintcalculator.exe largeintcalculator.c

      - name: Compile on macOS
        if: matrix.os == 'macos-latest'
        run: gcc -o ${{env.BUILD_DIR}}/macos/largeintcalculator largeintcalculator.c

      - name: Display file sizes
        run: |
          du -h ${{env.BUILD_DIR}}/ubuntu/largeintcalculator
          du -h ${{env.BUILD_DIR}}/windows/x64/largeintcalculator.exe
          du -h ${{env.BUILD_DIR}}/windows/x86/largeintcalculator.exe
          du -h ${{env.BUILD_DIR}}/macos/largeintcalculator

      - name: Commit and push
        if: matrix.os == 'ubuntu-latest'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CodeByAidan"
          git pull
          git add .
          git commit -m "Add build outputs" || exit 0
          git push
