name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/builds/${{ runner.os }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/builds/${{ runner.os }} --config ${{env.BUILD_TYPE}}

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CodeByAidan"
          git pull
          git add .
          git diff-index --quiet HEAD || git commit -m "Add build outputs" && git push
        working-directory: ${{ github.workspace }}
