name: Build macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_DIR: builds

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug - List files before compilation
        run: |
          ls -R
          ls -R artifacts
          ls -R build
          ls -R .github/workflows
        shell: /bin/bash

      - name: Build and move artifacts
        run: |
          chmod +x .github/workflows/compile.sh
          .github/workflows/compile.sh macos
          mkdir -p build/macos
          mv artifacts/* build/macos/
        shell: /bin/bash -e {0}

      - name: Debug - List files after compilation
        run: |
          ls -R
          ls -R artifacts
          ls -R build
          ls -R .github/workflows
        shell: /bin/bash
